# Generated by Django 3.0.4 on 2020-11-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20201127_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=63)),
                ('City', models.CharField(max_length=63)),
                ('Cuisine_Style', models.CharField(max_length=127)),
                ('CommentsAverage', models.IntegerField()),
                ('countofcomments', models.IntegerField()),
                ('click', models.IntegerField()),
                ('Price_Range', models.CharField(max_length=31)),
                ('MAXPRICE', models.IntegerField()),
                ('MINPRICE', models.IntegerField()),
                ('link', models.CharField(max_length=127)),
                ('image_url', models.CharField(max_length=127)),
            ],
        ),
    ]
